version: "3"
services:
  mongo:
    image: mongo:6.0.13
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    networks:
      - network1
  survey-api:
    container_name: survey-api-container
    image: node:20.11
    working_dir: /usr/src/survey-api
    restart: always
    volumes:
      - ./dist:/usr/src/survey-api/dist
      - ./package.json:/usr/src/survey-api/package.json
      - ./package-lock.json:/usr/src/survey-api/package-lock.json
      - ./.env:/usr/src/survey-api/.env
    command: bash -c "npm ci --production && npm run debug"
    ports:
      - ${PORT}:3000
      - 9222:9222
    networks:
      - network1
    env_file:
      - .env
networks:
  network1:
    driver: bridge
