version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:6.0.13
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    networks:
      - network1
  survey-api:
    container_name: survey-api-container
    build: .
    image: "survey-api"
    restart: always
    command: npm start
    volumes:
      - ./dist:/usr/src/survey-api/dist
    ports:
      - 3000
    networks:
      - network1
networks:
  network1:
    driver: bridge
